#Test against this version of Node.js
environment:
  matrix:
   #node.js
   - nodejs_version: "7"

#Install scripts. (run afer repo cloning)
install:
  # Get the latest stabel version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# Post install scripts
test_script:
  # Output useful info for debugging
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build
build: off
